export DOCKER_DEFAULT_PLATFORM=linux/arm64/v8

up:
	docker compose up -d

rebuild:
	docker compose up --build -d

down:
	docker compose down --remove-orphans

clean:
	rm -rf `find . -name __pycache__`
	rm -f `find . -type f -name '*.py[co]' `
	rm -f `find . -type f -name '*~' `
	rm -f `find . -type f -name '.*~' `
	rm -rf `find . -name .pytest_cache`
	rm -rf *.egg-info
	rm -f report.html
	rm -f .coverage
	rm -rf {build,dist,site,.cache,.mypy_cache,.ruff_cache,reports}
