# Generated by Django 5.0.1 on 2024-02-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VIP", "VIP"),
                            ("BASIC", "BASIC"),
                            ("PRO", "PRO"),
                            ("TRIAL", "TRIAL"),
                        ],
                        max_length=10,
                    ),
                ),
                ("max_ats_count", models.IntegerField()),
                ("max_backtests", models.IntegerField()),
                ("max_optimizations", models.IntegerField()),
                ("backtest_duration_days", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name="userstatus",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statuses",
                to="main_service.statuses",
            ),
        ),
    ]
