# Generated by Django 5.0.1 on 2024-02-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_service", "0002_statuses_alter_userstatus_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuses",
            name="cost",
            field=models.CharField(
                choices=[
                    ("VIP", "VIP"),
                    ("BASIC", "BASIC"),
                    ("PRO", "PRO"),
                    ("TRIAL", "TRIAL"),
                ],
                max_length=255,
            ),
        ),
    ]
