# Generated by Django 5.0.1 on 2024-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_service", "0003_alter_statuses_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuses",
            name="max_investment",
            field=models.IntegerField(default=100),
        ),
    ]
