# Generated by Django 5.0.1 on 2024-02-20 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_service", "0004_statuses_max_investment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statuses",
            old_name="backtest_duration_days",
            new_name="backtest_and_optimization_duration_days",
        ),
        migrations.RenameField(
            model_name="userstatus",
            old_name="backtest_duration_days",
            new_name="backtest_and_optimization_duration_days",
        ),
        migrations.RemoveField(
            model_name="userstatus",
            name="optimization_duration_days",
        ),
    ]
