# Generated by Django 5.0.1 on 2024-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_service",
            "0005_rename_backtest_duration_days_statuses_backtest_and_optimization_duration_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="num_of_ats",
            field=models.IntegerField(default=1),
        ),
    ]
