# Generated by Django 5.0.1 on 2024-03-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_service", "0006_customuser_num_of_ats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backtestandoptimizationhistory",
            name="pnl",
            field=models.CharField(max_length=255),
        ),
    ]
