# Generated by Django 5.0.1 on 2024-04-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_service", "0007_alter_backtestandoptimizationhistory_pnl"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestandoptimizationhistory",
            name="final_progress_number",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="backtestandoptimizationhistory",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="backtestandoptimizationhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("success", "Success"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
