# Generated by Django 5.0.1 on 2024-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_service",
            "0008_backtestandoptimizationhistory_final_progress_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestandoptimizationhistory",
            name="exchange",
            field=models.CharField(default="bybit", max_length=255),
        ),
    ]
