# Generated by Django 5.0.1 on 2024-05-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_service", "0009_backtestandoptimizationhistory_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
