version: "3.4"

services:
  app:
    build: grid_project
    restart: always
    container_name: app
    volumes:
      - ./:/usr/src/project/
    working_dir: /usr/src/project/
    command: python -m src
