# Generated by Django 5.0.1 on 2024-02-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotsStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("qty", models.FloatField()),
                ("realized_pnl", models.FloatField()),
                ("quote_qty", models.FloatField()),
                ("commission", models.FloatField()),
                ("open_time", models.DateTimeField(blank=True, null=True)),
                ("close_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CryptoTradingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trading_pair", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("price_change_in_24h", models.FloatField()),
                ("volume_change_in_24h", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="OptimizedStrategies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("optimized_settings", models.JSONField()),
                ("json_data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="TradingBots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=100)),
                ("exchange", models.CharField(max_length=25)),
                ("launch_date", models.DateTimeField(default="2024-02-15 20:05:22")),
                ("running_time", models.CharField(default="0 days", max_length=25)),
                ("investment_amount", models.FloatField(default=0)),
                ("leverage", models.IntegerField()),
                ("margin_type", models.CharField(max_length=10)),
                ("trading_pair", models.CharField(max_length=100)),
                ("entry_price", models.FloatField(default=0)),
                ("profit", models.FloatField(default=0)),
                ("approximately_price_year", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("stopped", "stopped"),
                            ("started", "started"),
                            ("inactive", "inactive"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("minimal_investment", models.FloatField(default=0)),
            ],
        ),
    ]
