# Generated by Django 5.0.1 on 2024-02-15 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crypto_service", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="botsstatistic",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="optimizedstrategies",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tradingbots",
            name="optimized_strategy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="crypto_service.optimizedstrategies",
            ),
        ),
        migrations.AddField(
            model_name="tradingbots",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="botsstatistic",
            name="trading_bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crypto_service.tradingbots",
            ),
        ),
    ]
