# Generated by Django 5.0.1 on 2024-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_service", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingbots",
            name="launch_date",
            field=models.DateTimeField(default="2024-02-15 20:06:26"),
        ),
    ]
