# Generated by Django 5.0.1 on 2024-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_service", "0022_alter_tradingbots_launch_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingbots",
            name="launch_date",
            field=models.DateTimeField(default="2024-02-28 11:59:12"),
        ),
    ]
