# Generated by Django 5.0.1 on 2024-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_service", "0131_alter_tradingbots_launch_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizedstrategies",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("Jumper", "jumper"),
                    ("Expo Grid", "expo_grid"),
                    ("Tango", "Tango"),
                ],
                default="Jumper",
                max_length=10,
            ),
        ),
    ]
