# Generated by Django 5.0.1 on 2024-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_service", "0132_optimizedstrategies_strategy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optimizedstrategies",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("jumper", "jumper"),
                    ("expo_grid", "expo_grid"),
                    ("tango", "tango"),
                ],
                default="jumper",
                max_length=10,
            ),
        ),
    ]
