# Generated by Django 5.0.1 on 2024-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_service", "0134_alter_optimizedstrategies_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="botsstatistic",
            name="unrealized_pnl",
            field=models.FloatField(default=0),
        ),
    ]
