# Generated by Django 5.0.1 on 2024-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_service", "0135_botsstatistic_unrealized_pnl"),
    ]

    operations = [
        migrations.AddField(
            model_name="optimizedstrategies",
            name="exchange",
            field=models.CharField(default="bybit", max_length=25),
        ),
    ]
