# Generated by Django 4.2.7 on 2023-11-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backtest_and_optimizer_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestF1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chosen_strategy", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=255)),
                ("days_of_backtest", models.IntegerField()),
                ("just_backtest", models.BooleanField()),
                ("interval_for_backtest", models.FloatField()),
                ("start_balance", models.FloatField()),
            ],
        ),
    ]
