# Generated by Django 4.2.7 on 2024-02-07 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backtest_and_optimizer_api", "0002_backtestf1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bus",
        ),
    ]
